"""MLX + DFlash speculative decoding backend (Apple Silicon).

Two-process backend:
- ``dflash-serve`` on 127.0.0.1:8001 — NVFP4 target + DFlash drafter, OpenAI API.
- ``litellm`` on 127.0.0.1:8000 — translates Anthropic /v1/messages into
  OpenAI /v1/chat/completions for Claude Code.

dflash-serve has no native Anthropic adapter, so the LiteLLM front-door is
required today. If a future dflash-mlx release adds /v1/messages we can drop
LiteLLM and become a single-process backend.
"""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
from pathlib import Path
from typing import ClassVar

import click
import httpx

from .base import Backend, clear_active_state, save_active_state

DRAFTER_REPO = "z-lab/Qwen3.6-35B-A3B-DFlash"
BACKEND_PORT = 8001  # dflash-serve, OpenAI-compat, localhost-only
FRONTDOOR_PORT = 8000  # LiteLLM, exposes Anthropic /v1/messages
LITELLM_KEY = "sk-autosre-local"  # master key for the local proxy

PIP_PACKAGES = (
    "dflash-mlx",
    "vllm-mlx",
    "litellm[proxy]",
    "huggingface_hub",  # `hf` CLI is now a base entry point (no [cli] extra)
)

# Trailing slash REQUIRED — openai-python urljoin strips /v1 without it,
# yielding /chat/completions and a 404 from dflash-serve. hosted_vllm/ provider
# routes Anthropic input to /v1/chat/completions instead of /v1/responses.
LITELLM_YAML_TMPL = """\
# Generated by autosre mlx-dflash backend.
# model_name == repo so callers can use the HF path directly via Anthropic API.
model_list:
  - model_name: {repo}
    litellm_params:
      model: hosted_vllm/{repo}
      api_base: http://127.0.0.1:{backend_port}/v1/
      api_key: sk-local

litellm_settings:
  drop_params: true
  request_timeout: 600

general_settings:
  master_key: {master_key}
"""


class MlxDflashBackend(Backend):
    """dflash-serve + LiteLLM. Apple Silicon only."""

    name = "mlx-dflash"
    description = "MLX + DFlash speculative decoding (Apple Silicon)"

    api_port = FRONTDOOR_PORT  # what get_claude_env / Claude Code talks to

    models: ClassVar[dict[str, str]] = {
        "qwen3.6": "mlx-community/Qwen3.6-35B-A3B-nvfp4",
        "qwen3.6-bf16": "mlx-community/Qwen3.6-35B-A3B-bf16",
        "qwen3.6-8bit": "unsloth/Qwen3.6-35B-A3B-MLX-8bit",
        "qwen3.6-4bit": "mlx-community/Qwen3.6-35B-A3B-4bit",
    }
    default_model = "qwen3.6"

    @property
    def home_dir(self) -> Path:
        d = self.data_dir / "mlx-dflash"
        d.mkdir(parents=True, exist_ok=True)
        return d

    @property
    def venv_dir(self) -> Path:
        return self.home_dir / "venv"

    @property
    def litellm_config(self) -> Path:
        return self.home_dir / "litellm.yaml"

    def _venv_bin(self, name: str) -> Path:
        return self.venv_dir / "bin" / name

    # ---------------------------------------------------------------- requirements

    def check_requirements(self) -> tuple[bool, list[str]]:
        missing: list[str] = []
        if platform.system() != "Darwin" or platform.machine() != "arm64":
            missing.append("macOS arm64 (Apple Silicon) - this backend is M-series only")
        if not self._find_python():
            missing.append("Python 3.10-3.13 (3.14 wheels for orjson are unavailable)")
        return len(missing) == 0, missing

    @staticmethod
    def _find_python() -> Path | None:
        """Find a Python 3.10-3.13 interpreter.

        ``orjson`` (a LiteLLM transitive dep) has no 3.14 wheel and source-builds
        fail against the 3.14 ABI, so we exclude 3.14 even when it's the
        mise-pinned default.
        """
        supported = {(3, 10), (3, 11), (3, 12), (3, 13)}
        candidates: list[Path] = []
        mise_installs = Path.home() / ".local" / "share" / "mise" / "installs" / "python"
        if mise_installs.exists():
            for child in sorted(mise_installs.iterdir(), reverse=True):
                py = child / "bin" / "python"
                if py.exists():
                    candidates.append(py)
        for n in ("python3.12", "python3.11", "python3.13", "python3.10", "python3"):
            p = shutil.which(n)
            if p:
                candidates.append(Path(p))
        matches: list[tuple[tuple[int, int], Path]] = []
        for py in candidates:
            try:
                r = subprocess.run(
                    [str(py), "-c", "import sys;print(sys.version_info[:2])"],
                    capture_output=True,
                    text=True,
                    check=True,
                    timeout=5,
                )
                parts = r.stdout.strip().strip("()").split(",")
                v: tuple[int, int] = (int(parts[0]), int(parts[1]))
                if v in supported:
                    matches.append((v, py))
            except Exception:
                continue
        if not matches:
            return None
        # Prefer 3.12, then descending version (newest 3.13 over 3.10).
        matches.sort(key=lambda m: (0 if m[0] == (3, 12) else 1, -m[0][0], -m[0][1]))
        return matches[0][1]

    # ---------------------------------------------------------------- setup

    def setup(self, force: bool = False, **kwargs: object) -> bool:
        click.secho("=== MLX + DFlash backend setup ===", fg="cyan", bold=True)

        ok, missing = self.check_requirements()
        if not ok:
            for m in missing:
                click.secho(f"  - {m}", fg="red")
            return False

        if force and self.venv_dir.exists():
            click.echo(f"--force: removing {self.venv_dir}")
            shutil.rmtree(self.venv_dir)

        if not self.venv_dir.exists():
            python = self._find_python()
            assert python is not None  # check_requirements above
            click.echo(f"Creating venv at {self.venv_dir} (using {python})")
            subprocess.run([str(python), "-m", "venv", str(self.venv_dir)], check=True)
        else:
            click.echo(f"Venv exists at {self.venv_dir}")

        pip = self._venv_bin("pip")
        click.echo("pip install --upgrade pip")
        subprocess.run([str(pip), "install", "--quiet", "--upgrade", "pip"], check=True)
        click.echo(f"pip install {' '.join(PIP_PACKAGES)}")
        subprocess.run(
            [str(pip), "install", "--quiet", "--upgrade", *PIP_PACKAGES],
            check=True,
            timeout=1800,
        )

        # Optional: prefetch the default model so first start() doesn't block.
        skip_download = bool(kwargs.get("skip_download", False))
        if not skip_download:
            self._hf_download(self.models[self.default_model])
            self._hf_download(DRAFTER_REPO)

        self._write_litellm_config(self.models[self.default_model])

        click.secho("Setup complete.", fg="green")
        return True

    def _hf_download(self, repo: str) -> None:
        hf = self._venv_bin("hf")
        if not hf.exists():
            click.secho("hf binary missing - pip install may have failed", fg="red")
            raise RuntimeError("hf binary missing in venv")
        click.echo(f"hf download {repo}")
        env = os.environ.copy()
        token = env.get("HF_TOKEN")
        if token:
            env["HUGGINGFACE_HUB_TOKEN"] = token
        subprocess.run([str(hf), "download", repo], env=env, check=True, timeout=7200)

    def _write_litellm_config(self, repo: str) -> None:
        content = LITELLM_YAML_TMPL.format(
            repo=repo,
            backend_port=BACKEND_PORT,
            master_key=LITELLM_KEY,
        )
        self.litellm_config.write_text(content)
        click.echo(f"Wrote {self.litellm_config}")

    # ---------------------------------------------------------------- claude

    def get_claude_env(self) -> dict[str, str]:
        return {
            "ANTHROPIC_BASE_URL": f"http://localhost:{self.api_port}",
            "ANTHROPIC_AUTH_TOKEN": LITELLM_KEY,
            "CLAUDE_CODE_ATTRIBUTION_HEADER": "0",
        }

    def get_claude_model_arg(self, model: str) -> str:
        # LiteLLM model_name == HF repo, so the API expects the repo string.
        return self.get_model_id(model)

    # ---------------------------------------------------------------- health

    def is_healthy(self) -> bool:
        # LiteLLM is the user-facing port; if it's up, the chain is up.
        try:
            with httpx.Client(timeout=2) as client:
                r = client.get(f"http://localhost:{self.api_port}/health/readiness")
                return r.status_code == 200
        except Exception:
            return False

    def _backend_healthy(self) -> bool:
        try:
            with httpx.Client(timeout=2) as client:
                r = client.get(f"http://localhost:{BACKEND_PORT}/v1/models")
                return r.status_code == 200
        except Exception:
            return False

    # ---------------------------------------------------------------- start / stop

    def start(
        self,
        model: str | None = None,
        foreground: bool = False,
        **kwargs: object,  # noqa: ARG002
    ) -> dict[str, object]:
        if not self.venv_dir.exists():
            raise RuntimeError("MLX backend not set up. Run: autosre setup -b mlx-dflash")

        model_key = model or self.default_model
        repo = self.get_model_id(model_key)
        if repo not in self.models.values():
            # User passed an unknown short key — treat as raw HF repo path.
            repo = model_key
        click.echo(f"Target: {repo}")
        click.echo(f"Drafter: {DRAFTER_REPO}")

        # Regenerate litellm.yaml so served_model_name maps to the chosen repo.
        self._write_litellm_config(repo)

        self._stop_tracked_processes()

        backend_cmd = [
            str(self._venv_bin("dflash-serve")),
            "--model",
            repo,
            "--draft",
            DRAFTER_REPO,
            "--port",
            str(BACKEND_PORT),
        ]
        litellm_cmd = [
            str(self._venv_bin("litellm")),
            "--config",
            str(self.litellm_config),
            "--host",
            "127.0.0.1",
            "--port",
            str(self.api_port),
        ]

        click.secho("=== Starting dflash-serve ===", fg="cyan", bold=True)
        click.echo(" ".join(backend_cmd))
        backend = subprocess.Popen(
            backend_cmd,
            stdout=None if foreground else subprocess.DEVNULL,
            stderr=None if foreground else subprocess.DEVNULL,
        )

        # dflash-serve takes a while to load 20GB; wait for /v1/models.
        click.echo("Waiting for dflash-serve to load weights...")
        ok = self._wait_for_server(f"http://localhost:{BACKEND_PORT}/v1/models", timeout=300)
        if not ok:
            backend.kill()
            raise RuntimeError("dflash-serve failed to come up within 5 minutes")
        click.secho("dflash-serve ready.", fg="green")

        click.secho("=== Starting LiteLLM Anthropic front-door ===", fg="cyan", bold=True)
        click.echo(" ".join(litellm_cmd))
        litellm = subprocess.Popen(
            litellm_cmd,
            stdout=None if foreground else subprocess.DEVNULL,
            stderr=None if foreground else subprocess.DEVNULL,
        )
        ok = self._wait_for_server(f"http://localhost:{self.api_port}/health/readiness", timeout=60)
        if not ok:
            litellm.kill()
            backend.kill()
            raise RuntimeError("LiteLLM failed to come up within 60s")
        click.secho("LiteLLM ready.", fg="green")
        click.echo(f"Anthropic Messages API: http://localhost:{self.api_port}/v1/messages")

        pids: dict[str, object] = {
            "dflash-serve": backend.pid,
            "litellm": litellm.pid,
            "model": repo,
        }
        self._save_pids(pids)
        save_active_state(
            {
                "backend": self.name,
                "model": model_key,
                "api_port": self.api_port,
            }
        )

        return {"pids": pids, "model": repo, "api_port": self.api_port}

    def stop(self, **kwargs: object) -> bool:  # noqa: ARG002
        # Stop LiteLLM first (front-door), then dflash-serve (heavy).
        pids = self._load_pids()
        stopped_any = False
        for name in ("litellm", "dflash-serve"):
            pid = pids.get(name)
            if isinstance(pid, int) and self._stop_process(pid, name):
                stopped_any = True
        self._clear_pids()
        clear_active_state()
        return stopped_any

    def status(self) -> dict[str, object]:
        pids = self._load_pids()
        return {
            "backend": self.name,
            "server_running": self.is_healthy(),
            "backend_running": self._backend_healthy(),
            "pids": {k: v for k, v in pids.items() if isinstance(v, int)},
            "model": pids.get("model"),
            "api_port": self.api_port,
            "backend_port": BACKEND_PORT,
        }
